name: Hello Pereira Tech Talk 
run-name: PereiraTechTalk Workflow ${{ github.run_id }}
on :
  push:
  workflow_dispatch:

jobs: 
  build:
    name: 'Build Software'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    steps: 
      - name: checkout code
        id: checkout
        uses: actions/checkout@v4
        
      - name: Welcome
        if: steps.checkout.outcome == 'success'
        run: | 
          echo "Hello Pereira Tech Talks Members"
          env
  test:
    needs: build
    name: 'Test Software'
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        id: checkout
        uses: actions/checkout@v4
      - name: Welcome
        if: steps.checkout.outputs.changed == 'true'
        run: | 
          echo "Another Job"
  deploy:
    needs: [build, test]
    name: 'Deploying Software'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: sh
    steps:
      - name: checkout code
        id: checkout
        uses: actions/checkout@v4
      - name: Welcome
        if: steps.checkout.outputs.changed == 'true'
        run: |
          echo "Deployment Job Pereira Tech Talks Members"
